# Generated by Django 3.1 on 2020-08-31 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('eng_word', models.CharField(max_length=32)),
                ('rus_word', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Часть речи',
                'verbose_name_plural': 'Части речи',
                'db_table': 'engvoc_part',
            },
        ),
        migrations.CreateModel(
            name='Rus',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Слово по-русски',
                'verbose_name_plural': 'Слова по-русски',
                'db_table': 'engvoc_rus',
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('eng_word', models.CharField(max_length=32)),
                ('rus_word', models.CharField(max_length=32)),
                ('kids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='djbook.taxonomy')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='djbook.taxonomy')),
            ],
            options={
                'verbose_name': 'Таксономия',
                'verbose_name_plural': 'Таксономии',
                'db_table': 'engvoc_tax',
            },
        ),
        migrations.CreateModel(
            name='Eng',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=32)),
                ('parts', models.ManyToManyField(to='djbook.Part')),
                ('taxonomies', models.ManyToManyField(to='djbook.Taxonomy')),
                ('translations', models.ManyToManyField(to='djbook.Rus')),
            ],
            options={
                'verbose_name': 'Слово по-английски',
                'verbose_name_plural': 'Слова по-английски',
                'db_table': 'engvoc_eng',
            },
        ),
    ]
