# Generated by Django 3.1 on 2020-08-31 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eng',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False, verbose_name='ИД'),
        ),
        migrations.AlterField(
            model_name='eng',
            name='word',
            field=models.CharField(max_length=32, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='part',
            name='eng_word',
            field=models.CharField(max_length=32, verbose_name='Англ'),
        ),
        migrations.AlterField(
            model_name='part',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False, verbose_name='ИД'),
        ),
        migrations.AlterField(
            model_name='part',
            name='rus_word',
            field=models.CharField(max_length=32, verbose_name='Рус'),
        ),
        migrations.AlterField(
            model_name='rus',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False, verbose_name='ИД'),
        ),
        migrations.AlterField(
            model_name='rus',
            name='word',
            field=models.CharField(max_length=32, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='eng_word',
            field=models.CharField(max_length=32, verbose_name='Англ'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False, verbose_name='ИД'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='kids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='djbook.taxonomy'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ancestors', to='djbook.taxonomy'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='rus_word',
            field=models.CharField(max_length=32, verbose_name='Рус'),
        ),
    ]
