# Generated by Django 3.1 on 2020-08-31 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbook', '0006_auto_20200831_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='kids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='djbook.taxonomy', verbose_name='Потомки'),
        ),
    ]
