# Generated by Django 3.1 on 2020-09-01 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbook', '0008_auto_20200901_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ancestor', to='djbook.taxonomy', verbose_name='Предок'),
        ),
    ]
