# Generated by Django 3.1 on 2020-09-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbook', '0009_auto_20200901_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='kids',
        ),
    ]
