# Generated by Django 3.1 on 2020-09-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbook', '0010_remove_taxonomy_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='slug',
            field=models.SlugField(default='aaaaaaaaaaa', max_length=32, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
