# Generated by Django 3.1 on 2020-09-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbook', '0011_taxonomy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eng',
            name='parts',
            field=models.ManyToManyField(related_name='eng', to='djbook.Part'),
        ),
        migrations.AlterField(
            model_name='eng',
            name='taxonomies',
            field=models.ManyToManyField(related_name='eng', to='djbook.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='eng',
            name='translations',
            field=models.ManyToManyField(related_name='eng', to='djbook.Rus'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='slug',
            field=models.SlugField(max_length=32, unique=True, verbose_name='Слаг'),
        ),
    ]
