# Generated by Django 3.1 on 2020-09-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbook', '0012_auto_20200902_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eng',
            name='parts',
        ),
        migrations.AddField(
            model_name='eng',
            name='parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part', to='djbook.part', verbose_name='Часть речи'),
        ),
    ]
