# Generated by Django 3.1 on 2020-09-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbook', '0013_auto_20200902_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eng',
            old_name='parts',
            new_name='part',
        ),
    ]
