# Generated by Django 3.1 on 2020-09-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbook', '0015_auto_20200902_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
