# Generated by Django 3.1 on 2020-09-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbook', '0016_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False, verbose_name='ИД'),
        ),
    ]
